ui: mocha-bdd
server: ./test/support/server.js
tunnel_host: http://focusaurus.com
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
browserify:
  - transform:
      name: babelify
      configFile: './.dist.babelrc'
